# configuration de docker-compose (exécuter une application multi-conteneur)

version: "3.9"  # optional since v1.27.0
services:
  joomla: 
    build: .  # donne le contexte (le Dockerfile)
    ports:
      - "8080:80"
    # restart: always
    links:
      - joomladb:mysql  
    volumes: # gauche dossier machine / droite dossier container
    # liaison des 2 conf
     - "./conf/joomla.conf:/etc/apache2/sites-available/joomla.conf" 

    # utilisation du fichiers avec les variables d'env
     - "./conf/initialisationApache.sh:/initialisationApache.sh" 


    # - "../:/var/www/html/joomla"
    # - "./config/apache.conf:/etc/apache2/site-avaible/apache.conf" # pour lancer le apache.conf si on utilise directement une image apache

    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example  


  joomladb: # ajout d'une image de BDD mysql à joomla
    image: mysql:5.6
    ports:
      - 3306
    # restart: always
    volumes: #création automatique 
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example


# volumes:
#   logvolume01: {}